name: MagPySV
dependencies:
- openssl=1.0.2l=0
- pip=9.0.1=py36_1
- python=3.6.1=2
- readline=6.2=2
- setuptools=27.2.0=py36_0
- sqlite=3.13.0=0
- tk=8.5.18=0
- wheel=0.29.0=py36_0
- xz=5.2.2=1
- zlib=1.2.8=3
- pip:
  - alabaster==0.7.10
  - astroid==1.5.3
  - babel==2.4.0
  - bleach==2.0.0
  - certifi==2017.4.17
  - chardet==3.0.4
  - datetime==4.2
  - decorator==4.0.11
  - docutils==0.13.1
  - entrypoints==0.2.3
  - geomag-webapp-interface==0.1.0
  - html5lib==0.999999999
  - idna==2.5
  - imagesize==0.7.1
  - ipykernel==4.6.1
  - ipython==6.1.0
  - ipython-genutils==0.2.0
  - isort==4.2.15
  - jedi==0.10.2
  - jinja2==2.9.6
  - jsonschema==2.6.0
  - jupyter-client==5.1.0
  - jupyter-core==4.3.0
  - lazy-object-proxy==1.3.1
  - markupsafe==1.0
  - mccabe==0.6.1
  - mistune==0.7.4
  - nbconvert==5.2.1
  - nbformat==4.3.0
  - numpydoc==0.7.0
  - pandocfilters==1.4.1
  - pep8==1.7.0
  - pexpect==4.2.1
  - pickleshare==0.7.4
  - prompt-toolkit==1.0.14
  - psutil==5.2.2
  - ptyprocess==0.5.2
  - py==1.4.34
  - pyflakes==1.5.0
  - pygments==2.2.0
  - pylint==1.7.2
  - pyqt5==5.9
  - pytest==3.1.3
  - python-dateutil==2.6.0
  - pytz==2017.2
  - pyzmq==16.0.2
  - qtawesome==0.4.4
  - qtconsole==4.3.0
  - qtpy==1.2.1
  - requests==2.18.1
  - rope-py3k==0.9.4.post1
  - simplegeneric==0.8.1
  - sip==4.19.3
  - six==1.10.0
  - snowballstemmer==1.2.1
  - sphinx==1.6.3
  - sphinxcontrib-websupport==1.0.1
  - spyder==3.1.4
  - testpath==0.3.1
  - tornado==4.5.1
  - traitlets==4.3.2
  - urllib3==1.21.1
  - wcwidth==0.1.7
  - webencodings==0.5.1
  - wrapt==1.10.10
  - zope.interface==4.4.2

